- README.md
Previously, it was unclear when meetings are and what their agenda will be from the information provided in this repo.
This PR clarifies these points.
> Update readme with meeting information

- README.md
This PR changes the calendar links to the unified dfinity event calendar.
> Update links to calendar

- topics/consent-msg.md
This PR refactors the ICRC-21 errors to be more consistent with ICRC-1 and ICRC-2.
The changes are:
* CamelCase variants
* OK, Err variant as the top-level result
* Introduce `GenericError` as is available in ICRC-1 and ICRC-2
In addition, this PR fixes a type reference forgotten in #39.
> ICRC-21: Refactor error types

- topics/wallet-interaction-standard.md
Add a short section to specify the transport requirements.
> ICRC-25: Specify transport requirements

- topics/icrc_21_consent_msg.md
This is PR make ICRC-21 consistent with the renaming doen in #55.
> ICRC-21: Update standard to reflect signer rename in ICRC-25

- topics/icrc_25_signer_interaction_standard.md
This PR expands the relying party verification of responses received from the signer to also cover `rejected` and `done` canister calls. This addresses security finding F05.
> ICRC-25: Specify verification of rejected calls, addresses sec finding F05

- reference-implementations/icrc25/signer/src/App.js
- reference-implementations/icrc25/signer/src/agent.js
This PR simplifies the agent code in the signer by replacing it with the library implementation and a `transform` function that extracts the content map just before it is submitted.
> ICRC-25 ref impl: Simplify signer agent code

- topics/icrc_25_signer_interaction_standard.md
This PR fixes the error response definitions to adhere to the JSON-RPC 2.0 standard.
The errors are now identified by their 5-digit codes, where the first digit represents the version of the standard and the second digit defines the error's category. The categories defined for now are:
- General (x1xxx): errors whose cause can't be easily identified and categorized (e.g. Unknown error)
- Not supported (x2xxx): part of the message is not supported
- User action (x3xxx): the error occurred as a result of explicit user's action
- Network (x4xxx): network request failed
For example: 13002 suggests that it's an error defined in the version 1 of the standard and falls into the User action category.
> ICRC25 Error fixes

- topics/icrc_25_signer_interaction_standard.md
This PR splits the example messages into separate JSON blocks to make each one valid (JSON allows only one top-level object). This allows editors with JSON support to help with validation and formatting.
It also removes a comment, because they are not allowed in JSON.
> ICRC-25: Split examples into valid JSON blocks

- topics/icrc_25_signer_interaction_standard.md
This PR simplifies the standard by removing the option to select networks. There is currently little benefit in having that feature, but it adds complexity to the standard.
If the network selection becomes useful later on, we can still add it either as an extension or by publishing a new version of the standard.
> ICRC-25: Remove network selection

- reference-implementations/icrc25/relying-party/package-lock.json
- reference-implementations/icrc25/relying-party/package.json
- reference-implementations/icrc25/relying-party/src/App.js
This PR pulls in a library for IC signature verification.
> ICRC-25 ref impl: Replace signature verification code with library

- topics/icrc_25_signer_interaction_standard.md
Adds a missing clarification regarding the representation of a principal.
> ICRC-25: Clarify principal representation

- topics/icrc_31_get_principals.md
- topics/icrc_32_sign_challenge.md
- topics/icrc_33_call_canister.md
This PR fixes minor things regarding the extensions scopes:
- make sections more consistent
- adjust titles
- unify sign_challenge examples
> Make scopes section more consistent

- topics/icrc_25_signer_interaction_standard.md
This PR fixes errors in the ICRC-25 method examples, mostly related to the recent splitting of ICRC-25.
> ICRC-25: Fix errors in examples

- topics/icrc_25_signer_interaction_standard.md
Renaming occurences of ICRC-33 to ICRC-49.
> ICRC-33/49: Rename ICRC-33 to ICRC-49

- topics/icrc_31_get_principals.md
In alignment with #128 and #131:
* the `version` is dropped
* this includes the changes to the errors made in #142
* user interaction is made explicit
> ICRC-31: Drop version and specify user interaction

- topics/icrc_32_sign_challenge.md
Add examples of actual challenge signature with and without delegation.
> ICRC-32: Add examples

- .github/workflows/ci.yml
- reference-implementations/ICRC-21/src/lib.rs
Add a rust CI check for the reference implementation of ICRC-21.
> Add CI workflow for rust

- README.md
We decided last session to start meeting weekly until further notice.
> Adjust meeting frequency in the README

- .gitignore
I want to edit Markdown files in my favorite editor without its configuration files being suggested for inclusion in the repo.
> chore: .gitignore

- topics/icrc_29_window_post_message_transport.md
- topics/signer_standards_overview.md
> fix: typo "singer"

- topics/icrc_27_accounts.md
@frederikrothenberger @dostro Sorry after today's meeting can't help but not see this 😅
> Update and rename icrc_27_get_accounts.md to icrc_27_accounts.md

- README.md
Adjust readme to reflect decision of last WG session on meeting frequency.
> Adjust meeting frequency to bi-weekly again

- topics/icrc_35_webpage_apis.md
Align the format of the presentation of the badge to other documents - i.e. consistency.
> docs: format draft badge

- reference-implementations/ICRC-95/README.md
- reference-implementations/ICRC-95/icrc_95.js
A minimal reference implementation of ICRC-95.
Should only be merged after #206, otherwise having a reference implementation does not make a lot of sense...
> ICRC-95: reference implementation

- topics/icrc_112_batch_call_canister.md
Re-phrase and structure the processing section.
Move **Using ICRC-25 with ICRC-112** out of processing into its own **Leveraging ICRC-25** section and re-phrase.
Additionally, move **Notes** out of processing and re-phrase.
> Re-phrase and structure the processing section.

- topics/ICRC-21/examples/en_US/icrc1_transfer/anonymous/default.json
- topics/ICRC-21/examples/en_US/icrc1_transfer/anonymous/no_memo.json
- topics/ICRC-21/examples/en_US/icrc1_transfer/authenticated/default.json
- topics/ICRC-21/examples/en_US/icrc1_transfer/authenticated/no_memo.json
- topics/ICRC-21/examples/en_US/icrc2_approve/anonymous/default.json
- topics/ICRC-21/examples/en_US/icrc2_approve/anonymous/no_expiry.json
- topics/ICRC-21/examples/en_US/icrc2_approve/anonymous/no_expiry_memo.json
- topics/ICRC-21/examples/en_US/icrc2_approve/anonymous/no_memo.json
- topics/ICRC-21/examples/en_US/icrc2_approve/authenticated/default.json
- topics/ICRC-21/examples/en_US/icrc2_approve/authenticated/no_allowance.json
- topics/ICRC-21/examples/en_US/icrc2_approve/authenticated/no_allowance_expiry.json
- topics/ICRC-21/examples/en_US/icrc2_approve/authenticated/no_allowance_expiry_memo.json
- topics/ICRC-21/examples/en_US/icrc2_approve/authenticated/no_allowance_memo.json
- topics/ICRC-21/examples/en_US/icrc2_approve/authenticated/no_expiry.json
- topics/ICRC-21/examples/en_US/icrc2_approve/authenticated/no_expiry_memo.json
- topics/ICRC-21/examples/en_US/icrc2_approve/authenticated/no_memo.json
- topics/ICRC-21/examples/en_US/icrc2_transfer_from/anonymous/default.json
- topics/ICRC-21/examples/en_US/icrc2_transfer_from/anonymous/no_memo.json
- topics/ICRC-21/examples/en_US/nns_increase_dissolve_delay/anonymous/default.json
- topics/ICRC-21/examples/en_US/nns_stake_neuron/anonymous/default.json
- topics/ICRC-21/examples/en_US/nns_start_dissolving/anonymous/default.json
Update ICRC-21 examples, replacing text values with `Value` variants.
> Update ICRC-21 examples.
