topics/consent-msg.md

In order to separate the ICRC-21 mandated types and methods from other methods and types a canister might use, they should be prefixed with the standard name "icrc21_".
This PR introduces these prefixes. It also fixes a small inconsistency in the example.

Prefix ICRC-21 methods and types

---

topics/consent-msg.md

This adds a query method to the ICRC-21 canister interface to list the supported standards related to consent messages.

Introduce ICRC-21 supported standards query

---

topics/wallet-interaction-standard.md

This PR makes the links in the ICRC-25 draft point to the other referenced draft documents.

ICRC-25: Add links to draft documnets for CAIP-2 and ICRC-21

---

topics/icrc_25_signer_interaction_standard.md

This PR addresses the [security review](https://github.com/dfinity/wg-identity-authentication/issues/52) finding F03 by making the permission scope extensible. This allows to define additional properties of the permission scope object in the future, such as restricting the `canister_call` scope to just certain canisters, methods, or even arguments.
In addition, it also makes a formulation stricter that would have allowed signers to hand out more permissions than initially requested.

ICRC-25: Make permission scope extensible, addresses sec finding F03

---

topics/icrc_21_consent_msg.md

This PR changes the authentication requirements for the icrc21_consent_message method call:
* authentication is no longer mandatory: this improves the flow significantly for cold signers
* authentication may still give benefits, if supported by the target canister. This could potentially lead to better consent messages for hot signer that can make this call in an authenticated way.
Additionally, add a note about the upcoming change for `icrc21_consent_message` which changes it from an `update` call to a relicated query as soon as that feature is generally available.

ICRC-21: Adapt the authentication requirements for icrc21_consent_message

---

topics/icrc_25_signer_interaction_standard.md

This PR
* expands the section related to the transport requirements
* introduces the concept of session to track permission scope lifetime
* introduces a new message to revoke permission scopes
in order to address the [security review](https://github.com/dfinity/wg-identity-authentication/issues/52) findings F02 and F04.
It also removes a misleading part of the description in the `permission` message.

ICRC-25: Address sec findings F02, F04: permission revocation

---

topics/icrc_25_signer_interaction_standard.md

This PR removes redundant examples and improves
titles in the error sections.

ICRC-25: Remove redundant error examples

---

topics/icrc_21_consent_msg.md

This PR specifies the consent message context more clearly to help developers chose an appropriate message when developing their canister.
This context is also added to the example.

ICRC-21: Specify message context

---

topics/icrc_25_signer_interaction_standard.md

This PR namespaces all the methods and scopes to the standard that defines them, by adding a prefix indicating the standard.
In addition, the `permission` message is renamed to `icrc25_request_permission` to convey the action associated with permissions.

ICRC-25: Prefix RPC methods with icrc25_

---

topics/icrc_29_window_post_message_transport.md

This PR makes the JSON-RPC 2.0 method prefix consistent with ICRC-25 messages.

ICRC-29: Make method prefix consistent with ICRC-25

---

topics/icrc_25_signer_interaction_standard.md

This PR replaces the content map with a CBOR encoded blob, which has the following advantages:
* get rid of complexity in this standard, by not requiring to define the internals of the content map
* remove possible encoding issues by simply using the same encoding as the interface specification

ICRC-25: Replace content map JSON object with blob

---

topics/icrc_25_signer_interaction_standard.md

This PR specifies that signers must also be able to process batch calls. This is relevant for an upcoming PR that separates the current `icrc25_request_permission` method into 2 separate messages.

ICRC-25: Define batch call semantics

---

topics/icrc_25_signer_interaction_standard.md

Restructures the scopes:
* move types section further up so types can be referenced in the new scopes section
* add section explaining and defining scopes
* clean up repeated definition of scope objects
* introduce prerequisite subsection on each message to better structure the requirements for the RP to invoke a method

ICRC-25: Extract scope definition into it's own section

---

topics/icrc_25_signer_interaction_standard.md

This PR splits the identitiy information part of the existing `icrc25_request_permission` method into another method called `icrc25_get_identities`. This makes the methods more focused.
The PR also adds clarifying information about how user interaction should be handled for the given methods. In particular, it allows signers to skip user interaction if the user previously approved the same request.

ICRC-25: Split out identity information from `icrc25_request_permission` method

---

topics/icrc_25_signer_interaction_standard.md

This PR introduces the method icrc25_granted_permissions method to query currently granted permission scopes.
It also renames icrc25_request_permission to icrc25_request_permissions so that it better reflects that multiple different permissions can be requested / granted.

ICRC-25: Introduce method to query granted permissions

---

topics/icrc_25_signer_interaction_standard.md

This PR renames icrc25_get_identities to icrc25_managed_identities to make the name more expressive.

ICRC-25: Rename icrc25_get_identities to icrc25_managed_identities

---

topics/icrc_21_consent_msg.md

In order to make the use-case of ICEC-21 clearer, the method icrc21_consent_message is renamed to
icrc21_canister_call_consent_message.
This rename is in anticipation of extensions to ICRC-21 that will introduce their own flavour of `consent_message` methods.

ICRC-21: Make method name more descriptive

---

topics/icrc_29_window_post_message_transport.md

This PR improves the wording of ICRC-29 in a few places. It clarifies the steps required to continue a session after the relying party has closed the signer window.

ICRC-29: Improve various wordings

---

topics/icrc_25_signer_interaction_standard.md

As requested in the working group, the list of predefined errors is mentioned explictly to make it less likely that devs miss those errors codes.

ICRC-25: List predefined errors explicitly

---

topics/icrc_21_consent_msg.md

This PR simplifies & changes the `icrc21_error`
type to be more intuitive for developers.
In particular, it resolves the confusion around
`NotSupported` which could be interpreted in multiple ways.

ICRC-21: Make error categories more intuitive

---

topics/icrc_25_signer_interaction_standard.md

This PR improves various small issues in ICRC-25:
- Fix broken links
- Replace `list` with `array` where appropriate
- Rename `Messages` to `Methods` to be consistent with the wording in the scopes section
- Capitalize `Signer` in all sequence diagrams

ICRC-25: Wording improvements

---

topics/icrc_25_signer_interaction_standard.md

This PR is intended to enable the splitting of individual standards. Most important is to have a generic wildcard (`*`) scope for `icrc25_request_permissions`. The individual standards will later introduce specific scopes per method

ICRC-25: generic scope and example

---

topics/icrc_21_consent_msg.md

This refactors the ICRC-21 error handling to be more ergonomic and specific:
* The `opt` is dropped from the API in favor of the `ICRC-1/2` `generic_error`
* The non-generic errors are relieved from having to provide an error_code as the variant already indicates the type

ICRC-21: Refactor consent message error types

---

topics/icrc_25_signer_interaction_standard.md
topics/icrc_39_batch_calling.md

This PR intends to extract the following standard extensions:
- ICRC-39: Batch Calling
This is a collaborative change by @frederikrothenberger and @plitzenberger

ICRC-39: extract icrc-39_batch_calls

---

topics/signer_standards_overview.md

Adds a link to the draft of ICRC-27 to the signer overview.

Update signer overview reference to ICRC-27

---

topics/icrc_25_signer_interaction_standard.md

This fixes a typo and adds a clarifying sentence to the ICRC-25 errors section.

ICRC-25: Clean up error section

---

topics/icrc_25_signer_interaction_standard.md

Fix JSON typing in example to follow JSON RPC standard (should be integer)

Fix JSON typing in example to follow JSON RPC

---

README.md

This adds an invite link to the ICP dev community server on discord.

Add discord channel invite to readme

---

topics/icrc_21_consent_msg.md

When finalized, the standards need to be available in the ICRC repo. To not upend how this working group operates, we will continue in this repository while the standards are in draft. However, we prepare the drafts such that the transition is easy once finalize. To that end, we already point to the location where the standard will end up eventually when querying supported standards.

ICRC-21: Point standard link to ICRC repo

---

topics/icrc_25_signer_interaction_standard.md

When finalized, the standards need to be available in the ICRC repo. To not upend how this working group operates, we will continue in this repository while the standards are in draft. However, we prepare the drafts such that the transition is easy once finalize. To that end, we already point to the location where the standard will end up eventually when querying supported standards.

ICRC-25: Point standard links to ICRC repos

---

topics/icrc_25_signer_interaction_standard.md

This PR implements the decision taken in #128 for ICRC-25. This means that all `version` fields are dropped. This has an effect on errors as they used to include the version in the code. This is now simplified to just indicate the broader category with the first digit and the rest being incremental numbers for each error. The "unknown error" is dropped in favor of a "generic error" with a description to avoid unhelpful errors.
By dropping the `version` field, some requests have no `params` anymore. To not confuse readers by writing "Request: none", the heading is changed to "Request Params", to better align with the JSON RPC spec and to make it clear that there still is a request being sent.
For consistency, all "Response" headings are changed to "Result".

ICRC-25: Drop version and simplify errors

---

topics/icrc_32_sign_challenge.md

In alignment with #128 the `version` is dropped.

ICRC-32: Drop version

---

topics/icrc_49_call_canister.md

In alignment with #128:
* the `version` is dropped
* this includes the changes to the errors made in #142

ICRC-49: Drop version and align errors

---

topics/icrc_27_get_icrc_1_accounts.md

This PR drop `version` in alignment with #128. The errors are adjusted to that change as well.

ICRC-27: Drop version and align errors

---

topics/icrc_32_sign_challenge.md

This simplifies the result by flattening the outermost object. This object was initially created because the method used to be able to provide multiple signatures (which is no longer the case to avoid complexity).
In addition, the outermost `delegation` field is renamed to `signer_delegation`. This is consistent with `sender_delegation` in the canister call envelope and avoids having multiple `delegation` fields on different hierarchy levels.

ICRC-32: Simplify result and avoid duplication of delegation field name

---

topics/icrc_21_consent_msg.md

This PR future proofs ICRC-21 for the addition of a payment flow to be added later. It is highly likely, that if the consent messages get widely used, that some of them are only provided if they are paid for.
A concrete example of that is the `install_code` method on the management canister: If the provided wasm module is 2MB in size and the consent message is to include the SHA256 of that wasm moduel, empirical measurements have shown that producing such a message costs about 4.5B cycles, which is about $0.006.
If every consent message for all `install_code` calls was provided for free this would incur a significant aggregated cost on the IC as a platform.
While we do not want to introduce a payment flow immediately, we can at least prepare for the eventual introduction of such a flow by …

ICRC-21: Add PaymentRequired error variant

---

topics/icrc_39_batch_calling.md

Remove id requirements from ICRC-39 and clarify that the array positions of the received requests must be equal to the corresponding responses.
Closes #136.

Remove id requirements from ICRC-39

---

topics/icrc_49_call_canister.md

Add optional `nonce` parameter to ICRC-49 to allow a relying party to force a unique `requestId`.

ICRC-49: Add optional nonce

---

topics/icrc_25_signer_interaction_standard.md

This PR updates ICRC-25 with the following changes:
* Remove wildcard scope
* Make sessions optional
* Make user-interaction optional on `icrc25_request_permissions` when prompting the user on every invocation of extension methods
* Fix typo in sequence diagram of `icrc25_supported_standards`
* Adjust examples to #170

ICRC-25: Remove wildcard permission and support stateless signers

---

reference-implementations/ICRC-21/icrc21_reference_canister.did
reference-implementations/ICRC-21/src/lib.rs

Change the icrc21_supported_standards query to
icrc10_supported_standards to be in line with the changes made in #171.

Switch supported standards method to ICRC-10

---

topics/icrc_49_call_canister.md

Remove optional scope parameters to simplify the standard & interactions. Also removes the outdated reference to the `*` scope.

ICRC-49: Simplify scope

---

topics/icrc_29_window_post_message_transport.md

By changing from the notification to polling, the signer no longer relies on the `window.opener` to be available to signal its readiness.
This is allows the signer window to redirect to other domains before signalling ready.

ICRC-29: Switch from signer notification to polling

---

topics/icrc_29_window_post_message_transport.md

Updated the spec to allow for redirect by the signer to a different origin. Previously a PR was made to switch to polling to make this possible but e.g. the authentication part in the spec did not allow for a signer origin that changes due to e.g. a redirect.
Also a note has been added regarding closing the signer window.

ICRC-29 Allow redirect by signer to different origin

---

reference-implementations/ICRC-21/src/icrc21_types.rs
reference-implementations/ICRC-21/src/lib.rs
topics/ICRC-21/ICRC-21.did

In the ongoing implementation of consent messages in the ledger canisters timezone conversion was raised as an issue.
An optional UTC offset is added to the consent message metadata to address that requirement.

ICRC-21: Add UTC offset to consent message preferences

---

topics/icrc_25_signer_interaction_standard.md

This PR makes significant changes to the ICRC-25 permission model:
* The notion of a session has been removed. The state of permissions is considered permanent with respect to a specific relying party (subject to signer policy). This closes the gap between stateless and stateful signers.
* Permissions can now be requested implicitly by simply making use of a method, given the permission has not been explicitly denied before.
* `icrc25_revoke_permissions` has been removed as it is no longer applicable to the current permission model. Resetting permissions has been considered, but dismissed as relying parties could request denied permissions to be reset too (or, in case that is excluded, would lead to unintuitive API design).
* `icrc25_granted_permissions` has been changed to …

ICRC-25: Change permission model to support ask-on-(first-)use

---

topics/icrc_27_accounts.md
topics/icrc_49_call_canister.md

Since the ICRC-25 rework in #185 there is no longer a concept of session. Hence the prerequisites in ICRC-27 and ICRC-49 need to be adjusted.

ICRC-27, ICRC-49: Remove active session prerequisite

---

topics/icrc_29_window_post_message_transport.md

I had a bit of trouble understanding the "Signer" and "Relying party" chapters of ICRC-29. The content was clear, but it took a few reads to piece everything together.
So, here's a PR with minor formatting suggestions for those two chapters.
The PR also adds a reference to MDN for the `message` event.
- Invert order of the chapters (because the communication is initiated by the relying party)
- Mark some comment as markdown comments
- Add a link to message on mdn
- Join two sentences

docs: ICRC-29 formatting

---

topics/icrc_25_signer_interaction_standard.md

There was two small typos in `icrc25_permissions`. It mentionned "grandted" permissions only while the response and standard actually list all permissions, not only those that are granted.

docs: typo granted in permissions

---

topics/icrc_27_accounts.md

"Get Accounts" was renamed some time ago to "Accounts". This PR fixes letfovers in the docs.

docs: fix leftovers Get Accounts -> Accounts

---

topics/icrc_27_accounts.md
topics/icrc_49_call_canister.md

Clarify the permission check step in message processing to be aligned with the 3-state permission change previously made in ICRC-25 (see #185).

ICRC-27/49: Clarify permission check

---

topics/icrc_28_trusted_origins.md
topics/icrc_34_delegation.md

This PR resolves the findings with regards to confusing wording that were found in the prod sec review.
It also adds a recommendation for approval flows for tradable assets in ICRC-28 in order to guide developers looking to get rid of approvals when interacting with ledgers.

ICRC-28/34: Clarify confusing sections

---

topics/ICRC-21/icrc_21_consent_msg.md

This PR includes a validation step in the cold signer use-case to explicitly validate the `sender` property of the icrc21_consent_message request.
A note is added to the hot signer use-case to use the same identity (or the anonymous one) to fetch the consent message and sign the requested call.

ICRC-21: Add validation step for the consent message request sender

---

topics/ICRC-21/icrc_21_consent_msg.md

Incorporate feedback from @peterpeterparker that it was unclear which identity should be used by the signer to request the consent message.
Additionally, the requirements for fetching the consent message in the cold-signer use-case have been clarified as well.

ICRC-21: Clarify sender for consent message request

---

topics/icrc_25_signer_interaction_standard.md

The "Network" error category is renamed to "Transport Channel" to include any error related to communications with signer (and the signer with the IC).
A new error is introduced (4001) to communicate unexpected interruption of the communication channel between the rp and the signer. In particular this error can be used if the user dismisses the UI elements of the signer early without completing the interaction (i.e. close browser tab or extension window).

ICRC-25: Rename Network Error Category to Transport Channel

---

topics/icrc_49_call_canister.md

I spotted an invalid link in ICRC-49 to ICRC-21. I guess the latest was maved but, the link was not updated.

docs: fix link to icrc-21

---

topics/icrc_29_window_post_message_transport.md

As mentioned in earlier WG calls, relying on the window close status would be unreliable. The solution was proposed to use heartbeats to indicate to both the relying party and signer that they're available and ready to receive messages.
This PR updates the ICRC-29 standard to implement heartbeats with minimal changes from the signer side and removes the no longer relevant session references to ICRC-25.

Rephrase and add heartbeats to the ICRC-29 standard.

---

topics/icrc_112_batch_call_canister.md

Align request params with ICRC-49, additionally clarify that requests param is an array of arrays.

Align request params with ICRC-49

---

topics/icrc_25_signer_interaction_standard.md

Recommend to include other standards like tokens in ICRC-25 supported standards method response.
This will enable relying parties to identify which signers support the token standards needed by the relying party.

Recommend to include tokens in ICRC-25 supported standards
